### ISSUE TITLE
希望在后面增加最大值和最小值显示

### ISSUE THREAD

**Issue by acdxxx177** [silenceper/qanswer#10]
先多谢提供这么好的工具,在win10+Android完美运行(修改分辨率后)

希望在后面显示一行,结果总数最大值和最小值
答案出现频率一眼很容易分清,但是这个结果总数基本都在上万条以上,一眼很难看出哪个多点哪个少点,增加点对题目的判断

**Comment by silenceper** [comment]
可以考虑价格颜色区分 😆
